### ISSUE TITLE
User can add an item to the shopping cart

### ISSUE THREAD

**Issue by Benjamin-Gnewuch** [manofdirt/amaze-on#2]
User should be able to add an item to cart, the cart icon will update with a value of the number of items in it, and possibly a message letting the user know an item was added.

**Comment by manofdirt** [comment]
![cart](https://cloud.githubusercontent.com/assets/9812714/13338886/5fbdf078-dbd9-11e5-86c5-9f1ba6c24210.png)

**Comment by Benjamin-Gnewuch** [comment]
![rainforest-add-to-cart](https://cloud.githubusercontent.com/assets/9812714/14544032/dc0a9ee0-024b-11e6-9aa8-139061755be9.png)

**Comment by Benjamin-Gnewuch** [comment]
![screen shot 2016-04-14 at 2 20 15 pm](https://cloud.githubusercontent.com/assets/9812714/14544068/14fd4702-024c-11e6-87fd-5f7578b8ddcd.png)

![screen shot 2016-04-14 at 2 20 27 pm](https://cloud.githubusercontent.com/assets/9812714/14544073/1d040468-024c-11e6-83f9-926c5ce7e2c0.png)
